#logging:
#  level:
#    #        tk.mybatis: DEBUG
#    com.biocome.platform.guard: DEBUG
#spring:
#  application:
#    name: gate-guard
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#    default-property-inclusion: non_null
#  datasource:
#    name: test
#    url: jdbc:mysql://${MYSQL_HOST:192.168.3.228}:${MYSQL_PORT:8066}/ag_admin_v1?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
#    # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
#  sleuth:
#    enabled: true
#    http:
#      legacy:
#        enabled: true
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.3.228:8848
#    sentinel:
#      transport:
#        dashboard: 192.168.3.228:8080
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 2048MB
#      max-request-size: 2048MB
#sample:
#  zipkin:
#    # When enabled=false, traces log to the console. Comment to send to zipkin
#    enabled: false
#
#mybatis:
#  basepackage: com.biocome.platform.guard.mapper
#  xmlLocation: classpath:mapper/**/*.xml
#  mapper-locations: "classpath*:mapper/*.xml"
#
#server:
#  port: 8762
#
## 必须配置
#feign:
#  httpclient:
#    enabled: false
#  okhttp:
#    enabled: false
#
#ribbon:
#  eureka:
#    enabled: true
#  ReadTimeout: 100000
#  ConnectTimeout: 100000
#  MaxAutoRetries: 0
#  MaxAutoRetriesNextServer: 1
#  OkToRetryOnAllOperations: false
#
#hystrix:
#  threadpool:
#    default:
#      coreSize: 1000 ##并发执行的最大线程数，默认10
#      maxQueueSize: 1000 ##BlockingQueue的最大队列数
#      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 600000
#
#
## 配置swagger
#swagger:
#  enabled: true
#  base-package: com.biocome.platform.guard
#  title: gate-guard
#  version: 1.0.0.SNAPSHOT
#  description: 门禁管理服务
#  contact:
#    name: gate-guard
#
#auth:
#  serviceId: auth
#  user:
#    token-header: Authorization
#  client:
#    id: gate-guard
#    secret: 123456
#    token-header: x-client-token
#
##redis-cache 相关
#redis:
#  pool:
#    maxActive: 300
#    maxIdle: 100
#    maxWait: 1000
#  host: ${REDIS_HOST:192.168.10.224}
#  port:  ${REDIS_PORT:5379}
#  cluster:
#    nodes: ${REDIS_HOST:192.168.10.224}:${REDIS_PORT:5379},${REDIS_HOST:192.168.10.224}:${REDIS_PORT:5381},${REDIS_HOST:192.168.10.224}:${REDIS_PORT:5383}
#  password:
#  timeout: 0
#  commandTimeout: 5000
#  # 服务或应用名
#  sysName: gate-guard
#  enable: true
#  database: 0
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  security:
#    enabled: false
#
#differentBrandUri: "{BIOCOME:'192.168.10.224:8000/iacs',XIONGDI:'192.168.10.224:8000/iacs',LIZE:'192.168.10.224:8000/iacs',HAINENG:'192.168.10.224:8000/iacs'}"
#dictCode: "008"
#
#job:
#  getToken: 0 */1 * * * ?
#  deleteAdvert: 0 30 2 * * ?
#upload:
#  file:
#    path: /home/biocome/version